name: Deploy to Oxygen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Oxygen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Oxygen deployment
        uses: Shopify/oxygenctl-action@v2
        with:
          oxygen_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
